Gruntfile.js
lib/services/cloud-build-service.ts
package.json
server-configs/config-base.json
server-configs/config.json

Add logs for cloud builds

---

lib/bootstrap.ts
lib/commands/cloud-lib-version.ts
lib/definitions/cloud-build-service.d.ts
lib/definitions/package-info-service.d.ts
lib/services/cloud-build-service.ts
lib/services/package-info-service.ts
lib/services/service-proxy.ts
package.json
test/commands/cloud-build.ts

Return QR code info on cloud build
Merge after https://github.com/NativeScript/nativescript-cli/pull/2691
Ping @TsvetanMilanov @rosen-vladimirov

Return QR Code info on cloud build

---

.gitignore

Ignore IDEs

---

README.md
lib/definitions/cloud-build-service.d.ts
lib/definitions/package-info-service.d.ts
lib/services/cloud-build-service.ts

Add documentation for all publicly exposed methods, describe their definitons and usage.
Add JSDocs for all publicly available methods.
Remove outdated TODOs in the code.

Add documentation for available methods when requiring the lib

---

lib/bootstrap.ts
lib/constants.ts
lib/definitions/cloud-build-service.d.ts
lib/definitions/itms-services.d.ts
lib/itms-services-plist-helper.ts
lib/services/cloud-build-service.ts
package.json

In case we're building for iOS with an Ad Hoc provision we **can** generate a QR code.
In case we're building for iOS without an Ad Hoc provision we **cannot** generate a QR code.

Fix QR code generation

---

lib/services/cloud-build-service.ts

Fix getting the version of CLI and runtime when building in the cloud. Make sure we respect tns-core-modules version from package.json even if it is written as range ("~x.x.x") and use the range for getting correct versions.

Fix getting version for runtime and CLI

---

README.md
lib/definitions/authentication-service.d.ts
package.json

Change openAction return type

---

lib/bootstrap.ts
lib/cloud-device-emulator.ts
lib/commands/kill-server.ts
lib/definitions/emulators.d.ts
package.json

Ping @TomaNikolov @TsvetanMilanov @rosen-vladimirov 
Merge after https://github.com/telerik/cloud-device-emulator/pull/5

Introduce command to kill emulator server

---

lib/services/cloud-build-service.ts

We need to know what runtime version is used for build as incremental builds
have no logic of detecting one.

Add runtime version in local package.json

---

lib/cloud-device-emulator.ts
lib/definitions/emulators.d.ts
package.json
test/mobile/mobile-core/appetize-device-discovery.ts

Merge after https://github.com/telerik/cloud-device-emulator/pull/8
Ping @TomaNikolov @rosen-vladimirov

Make cloud-device-emulator implement IDisposable

---

lib/constants.ts
server-configs/config-dev.json
server-configs/config-local.json
server-configs/config-production.json
server-configs/config-test.json
server-configs/config.json

We need to change the names of our cloud services in the config files to be consistent with our server and jenkins.

Change services names

---

package.json

Bump dependency version

---

lib/definitions/authentication-service.d.ts
lib/services/authentication-service.ts
lib/services/cloud-services/cloud-request-service.ts
lib/services/user-service.ts

* Add missing await.
* Fix typo in refresh token name.

[Fix] Try to refresh token after the request failed.

---

lib/cloud-device-emulator.ts

Always kill server

---

lib/services/cloud-build-service.ts

Merge after https://github.com/NativeScript/nativescript-cli/pull/2883

Save build info file after build

---

lib/bootstrap.ts
lib/constants.ts
lib/definitions/emulators.d.ts
lib/mobile/device/cloud-emulator-application-manager.ts
lib/mobile/device/cloud-emulator-device-file-system.ts
lib/mobile/device/cloud-emulator-device.ts
lib/mobile/mobile-core/cloud-emulator-device-discovery.ts
lib/services/cloud-emulator-launcher.ts
lib/services/cloud-services/cloud-emulator-service.ts
package.json
test/mobile/mobile-core/cloud-emulator-device-discovery.ts

Ping @rosen-vladimirov @TsvetanMilanov 
Merge after https://github.com/telerik/cloud-device-emulator/pull/12

Rebranding

---

README.md

Rebrand readme

---

.gitignore
lib/bootstrap.ts
lib/constants.ts
lib/definitions/cloud-build-service.d.ts
lib/definitions/cloud-services/build-cloud-service.d.ts
lib/definitions/cloud-services/cloud-services.d.ts
lib/definitions/cloud-services/code-commit-service.d.ts
lib/definitions/git-service.d.ts
lib/helpers.ts
lib/services/cloud-build-service.ts
lib/services/cloud-services/build-cloud-service.ts
lib/services/cloud-services/code-commit-service.ts
lib/services/git-service.ts
package.json
resources/git/aws-credential-helper/code-commit-credential-helper.js
resources/git/aws-credential-helper/credential-helper
resources/git/template-.gitignore
server-configs/config-dev.json
server-configs/config-local.json
server-configs/config-production.json
server-configs/config-test.json
server-configs/config.json

* Create credential helper to authenticate git in aws code commit. 
* We will use git to upload only the diff between the cloud and the local repository. This way we will speed up the time for the cloud builds.

Use git to upload projects

---

lib/services/git-service.ts
package.json

* Fix Windows credential manager prompt.
* Fix "nothing to commit" error message test.

Fix Windows credential manager prompt.

---

lib/services/git-service.ts
package.json

* Missing update of sha.
* this.gitDirName will have the same value in a long living process.

Fix .git directory path.

---

README.md
lib/definitions/cloud-build-service.d.ts
package.json

Add the description for the new events in the cloudBuildService for the build steps.

Add build steps docs

---

Gruntfile.js
lib/bootstrap.ts
lib/cloud-options-provider.ts
lib/commands/build-command-helper.ts
lib/commands/cloud-build.ts
lib/commands/cloud-codesign.ts
lib/commands/cloud-publish.ts
lib/constants.ts
lib/definitions/build-command-helper.d.ts
lib/definitions/cloud-build-service.d.ts
lib/definitions/cloud-codesign-service.d.ts
lib/definitions/cloud-options.d.ts
lib/definitions/cloud-publish-service.d.ts
lib/definitions/cloud-service.d.ts
lib/definitions/cloud-services/build-cloud-service.d.ts
lib/definitions/cloud-services/cloud-services.d.ts
lib/definitions/emulators.d.ts
lib/services/cloud-build-service.ts
lib/services/cloud-codesign-service.ts
lib/services/cloud-publish-service.ts
lib/services/cloud-service.ts
lib/services/cloud-services/build-cloud-service.ts
lib/services/cloud-services/upload-service.ts
lib/services/upload-service.ts
package.json
server-configs/config.json

* Introduce publish command
* Introduce a `CloudOptionsProvider` used for managing additional `--` flags 
* Introduce publish service
* Extract some interfaces and cleanup some code
**NB!** Docs and tests are pending
Merge after https://github.com/NativeScript/nativescript-cli/pull/3128

Introduce publishing

---

README.md

The long-awaited addition to https://github.com/NativeScript/nativescript-cloud/pull/56

Add publish docs

---

README.md
lib/bootstrap.ts
lib/definitions/application-service.d.ts
lib/services/application-service.ts
package.json

Which can be queried about whether or not to build/install a given application on a given device.

Introduce applicationService

---

README.md

We have a breaking change in the Public API for the build which must be
documented in the README.md.

Update Public API in README.md

---

lib/commands/account/usage.ts
lib/definitions/cloud-services/accounts-cloud-service.d.ts
lib/services/cloud-services/accounts-cloud-service.ts
lib/services/cloud-services/cloud-request-service.ts
lib/services/cloud-services/cloud-services-proxy.ts
package.json

Our server now returns more info for the feature usage. We should use it.

Extend usage info

---

README.md

Add Contents section, so links to a specific part of the README can be easily sent to others.

Update README for easier linking

---

README.md

Fix documentation for acceptEula method - it does not return any value, so fix the README to show this.

Fix documentation for acceptEula method

---

lib/services/cloud-build-service.ts

Warn user whenever unable to use git

---

lib/services/git-service.ts

We need to check if the cloud remote is set correctly before we execute
our git operations. Currently if the remote is set to incorrect url we
will try to add it again and this will fail. We should change the wrong
remote url if the remote is added and if the remote url is incorrect.

 Check if cloud remote is correct

---

lib/services/cloud-build-service.ts

In older CLI versions the `prepareProject` method has different arguments. Fix the backwards compatibility by checking CLI's version and call the method with correct args.

Fix backwards compatibility with old CLI versions

---

lib/bootstrap.ts
lib/commands/account/usage.ts
lib/definitions/server/server-accounts-service.d.ts
lib/definitions/server/server-auth-service.d.ts
lib/definitions/server/server-build-service.d.ts
lib/definitions/server/server-code-commit-service.d.ts
lib/definitions/server/server-services.d.ts
lib/mobile/device/cloud-emulator-application-manager.ts
lib/services/accounts-service.ts
lib/services/authentication-service.ts
lib/services/cloud-build-service.ts
lib/services/cloud-codesign-service.ts
lib/services/cloud-emulator-launcher.ts
lib/services/cloud-publish-service.ts
lib/services/server/server-accounts-service.ts
lib/services/server/server-auth-service.ts
lib/services/server/server-build-service.ts
lib/services/server/server-code-commit-service.ts
lib/services/server/server-emulators-service.ts
lib/services/server/server-request-service.ts
lib/services/server/server-service-base.ts
lib/services/server/server-services-proxy.ts
lib/services/upload-service.ts
lib/services/user-service.ts
test/mobile/mobile-core/cloud-emulator-device-discovery.ts
test/services/cloud-emulator-service.ts

There's a lot of confusion with current services names. In order to resolve it, rename all server related services by following the conventions:
`nsCloudServer<service name>`. Rename `cloud-services` directories to `server`
Rename the files and methods as well:
nsCloudAccountsCloudService -> nsCloudServerAccountsService
nsCloudAuthCloudService -> nsCloudServerAuthService
nsCloudBuildCloudService -> nsCloudServerBuildService
nsCloudEmulatorService -> nsCloudServerEmulatorsService
nsCloudRequestService -> nsCloudServerRequestService
nsCloudCodeCommitService -> nsCloudServerCodeCommitService
nsCloudServicesProxy -> nsCloudServerServicesProxy
accounts-cloud-service.ts -> server-accounts-service.ts
auth-cloud-service.ts -> server-auth-service.ts
build-cloud-service.ts   -> …

Rename all server related services

---

README.md
lib/commands/build-command-helper.ts
lib/definitions/cloud-build-service.d.ts
lib/services/cloud-build-service.ts
package.json

* Fix README.md incorrect interface and set example on how to webpack
* Enable webpack from command-line
Ping @rosen-vladimirov @nadyaA

Enable webpacking in cloud

---

Gruntfile.js

Use default in rebuild grunt tasks

---

lib/services/cloud-service.ts
package.json

Instead of retrying two times with a second and a half interval retry using exponential backoff.
Use 8 retries each after double than the last's timeout. Start from a second and a half.

Check if build is running using exponential backoff

---

lib/cloud-options-provider.ts
lib/commands/build-command-helper.ts
lib/commands/cloud-codesign.ts
lib/commands/cloud-publish.ts
lib/definitions/cloud-build-service.d.ts
lib/definitions/cloud-codesign-service.d.ts
lib/definitions/cloud-options.d.ts
lib/definitions/cloud-publish-service.d.ts
lib/definitions/server/server-build-service.d.ts
lib/services/cloud-build-service.ts
lib/services/cloud-codesign-service.ts
lib/services/cloud-publish-service.ts

Add option to use shared cloud for all cloud operations.

Add option to use shared cloud

---

README.md
lib/commands/clean/clean-cloud-workspace.ts
lib/definitions/cloud-build-service.d.ts
lib/definitions/cloud-project-service.d.ts
lib/definitions/server/server-project-service.d.ts
lib/services/cloud-project-service.ts

Instead of accepting a number of arguments accept a single one

Change cleanupProject arg to object

---

lib/services/cloud-service.ts

Fix regression from https://github.com/NativeScript/nativescript-cloud/pull/91
With the current implementation the build status is checked with exponential backoff, however once we establish there is a `status.json` file we do not check its contents regularly.
This means the status won't ever change and the build will practically never end.
Fix this by separating the build process into two steps:
1. Check for `status.json` using the exponential backoff approach
1. Once `status.json` is created poll for output and status every few milliseconds
Ping @rosen-vladimirov @TsvetanMilanov @TomaNikolov

Fix check for output/status regularly

---

lib/cloud-options-provider.ts
lib/commands/build-command-helper.ts
lib/definitions/cloud-build-service.d.ts
lib/definitions/cloud-options.d.ts
lib/definitions/server/server-build-service.d.ts
lib/services/cloud-build-service.ts

Add new `--` flags to control the vm template and the workflow.
Ping @rosen-vladimirov @TomaNikolov

Add workflow/template options

---

Gruntfile.js
package.json

Exclude */doctor.d.ts from references.d.ts

Exclude */doctor.d.ts from references.d.ts

---

lib/bootstrap.ts
lib/commands/account/features.ts
lib/definitions/acccounts-service.d.ts
lib/definitions/server/server-accounts-service.d.ts
lib/services/accounts-service.ts
lib/services/server/server-accounts-service.ts

Add command that shows account features - which are enabled and which are disabled.
https://github.com/Icenium/fusion-services/pull/128

Add features command

---

README.md
lib/definitions/kinvey-service.d.ts
lib/definitions/server/mbaas-services/kinvey-auth-services.d.ts
lib/services/kinvey-service.ts

- Add JSDocs to the Kinvey service declarations.
- Update the public API with examples for the Kinvey service usage.
- Update the public API with examples for get account features usage.
- Add default value for the `redirectUri` property for Kinvey authentication service.

Add docs for Kinvey and get account features

---

lib/definitions/kinvey-service.d.ts
lib/definitions/server/mbaas-services/kinvey-auth-services.d.ts
lib/mobile/device/cloud-emulator-application-manager.ts
lib/services/kinvey-service.ts

- Change the `envronmentId` property in the changeDefaultAuthService input to `environmentId`.
- Handle 404 error on GET /auth-services in getDefaultAuthService method.

Fix Kinvey bugs

---

lib/services/cloud-service.ts

We need to change the cloud operation in progress status to be something
more generic.

Change Building status to InProgress

---

package.json
server-configs/config.json

Fix config

---

lib/services/eula-service-base.ts
test/services/eula-service.ts

This would make the server return 301 Not Modified status without returning the file content in case we already have it downloaded.

Add If-Modified-Since header to EULA GET request

---

lib/bootstrap.ts
lib/definitions/cloud-configuration-service.d.ts
lib/definitions/server/server-build-service.d.ts
lib/services/cloud-build-service.ts
lib/services/cloud-configuration-service.ts
lib/services/version-service.ts
test/services/version-service.ts

Includes:
* Introduce `cloud-configuration.json` file -> used for configuring cloud build options
* Respect `machineId` from `cloud-configuration.json`
Ping @rosen-vladimirov @TsvetanMilanov @Fatme

Introduce cloud-configuration file

---

lib/services/eula-service-base.ts

After adding the `If-Modified-Since` flag to http request for downloading EULA, the `tns accept eula` command fails as the server returns empty response and the `$httpClient` fails to `JSON.parse` the result.
So, the command fails as it must download the EULA. In order to fix the issue, force the download in such cases. The case is only one currently - when accepting the EULA. In such case force the download.

fix: `tns accept eula` command fails

---

README.md

Fix the documentation describing how to load the extension and use the
library.
Fixes https://github.com/NativeScript/nativescript-cloud/issues/121

docs: Fix documentation how to use extension

---

lib/services/cloud-build-service.ts

Related to https://github.com/NativeScript/sidekick-feedback/issues/277.

fix: Webpack variables are not transferred correctly during build

---

lib/cloud-options-provider.ts

Related to https://github.com/NativeScript/nativescript-cli/pull/4181

chore: add mandatory hasSensitiveValue field for cloud options

---

package.json

Bump the version to 1.16.0

---

lib/services/cloud-codesign-service.ts
package.json

Fix the codesign response object

Fix the codesign

---

lib/bootstrap.ts
lib/commands/cloud-run.ts
lib/services/cloud-encryption-service.ts
lib/services/cloud-encryption-settings-service.ts
package.json

The encryption service must not clone deep $usersSettingsService because
it will lead to start up of two cleanup processes and one of them will
live forever keeping the CLI alive!

Fix cloud build command hang

---

lib/services/cloud-platform-service.ts

Reverts NativeScript/nativescript-cloud#173

Revert "fix: provide nativePrepare correctly to deploy"
