- lib/services/cloud-build-service.ts
- package.json
Currently we rely on the information returned by the server in order to set the filename of the build output (.apk, .ipa..). However currently it does not work correctly and returns `undefined.apk`. Get back the previous code, which sets the name correctly.
> Fix the filename of the build output

- lib/services/cloud-build-service.ts
- lib/services/service-proxy.ts
- package.json
The ProjectName should be passed to Cloud Builds in order to generate correct output filename. In case it is not passed, the name is "undefined.apk", "undefined.ipa", etc.
Remove some obsolete comments.
For mobileprovisions we need the filename in S3 to be `<UUID of provision>.mobileprovision`, so make sure the name is this one.
Fix getting project project files for cloud builds - ignore all hidden files and include .ts files.
> Fix cloud builds

- lib/services/cloud-build-service.ts
- package.json
Fix getting the version of CLI and runtime when building in the cloud. Make sure we respect tns-core-modules version from package.json even if it is written as range ("~x.x.x") and use the range for getting correct versions.
> Fix getting version for runtime and CLI

- Gruntfile.js
In Gruntfile.js we try to get path to ios-device-lib, but we expect it to be at the root of node_modules.
However, when npm2 is used, the ios-device-lib is a dependency of nativescript.
So check where it is and use this path.
> Fix getting path to ios-device-lib

- Gruntfile.js
- README.md
- lib/bootstrap.ts
- lib/cloud-device-emulator.ts
- lib/constants.ts
- lib/definitions/cloud-services/cloud-services.d.ts
- lib/definitions/emulators.d.ts
- lib/mobile/device/appetize-application-manager.ts
- lib/mobile/device/appetize-device-file-system.ts
- lib/mobile/device/appetize-device.ts
- lib/mobile/mobile-core/appetize-device-discovery.ts
- lib/services/appetize-emulator-launcher.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-services/cloud-emulator-service.ts
- lib/services/cloud-services/upload-service.ts
- package.json
- test/mobile/mobile-core/appetize-device-discovery.ts
- test/services/cloud-emulator-service.ts
* Subscribe `appetizeDeviceDiscovery` to `$devicesService` and raise `deviceFound` and `deviceLost` events accordingly.
* Implement all the classes around `appetize-device` like `appetize-application-manager` and `appetize-device-file-system`
* Introduce public class `appetizeEmulatorLauncher` with method `startEmulator` that can start up emulators
* Implement `installApplication` in `appetize-application-manager` which enables `tns deploy` to work accordingly
* Restart the emulator upon reinstalling an app
Ping @rosen-vladimirov @TsvetanMilanov 
Merge after https://github.com/telerik/mobile-cli-lib/pull/963 and https://github.com/telerik/cloud-device-emulator/pull/4
> Introduce appetizeDeviceDiscovery

- README.md
- lib/definitions/authentication-service.d.ts
- lib/definitions/cloud-services/auth-cloud-service.d.ts
- lib/services/authentication-service.ts
- lib/services/cloud-services/auth-cloud-service.ts
We should add `cancelLogin` method because when we use the `nativescript-cloud` as a module in long living process we want to have a way to stop the current login session.
When we login our identity services sets a cookie. If we don't clear this cookie after logout we will automatically login the user on the next login request. We don't want this behavior so we should add request to `logout` endpoint on our server to clear the cookie. Because of this change we have a breaking change in our logout api - the logout method accepts optional options object with open action. This open action will be used to open the logout url.
> Improve authentication service.

- lib/commands/cloud-build.ts
- lib/definitions/cloud-build-service.d.ts
- lib/services/cloud-build-service.ts
* To trigger an incremental, build the build request data JSON
must set the property useIncrementalBuild to "true". This is the default
behavior. Using the --clean option will explicitly require
clean & full build.
* Although the nativescript-cloud is an extension that is used only with
nativescript projects, current implementation of the builder daemon will
not add default framework. This breaks tooling when incremental build is
performed. Passing the framework here is more consistent that adding conditional
behavior in the tooling.
http://teampulse.telerik.com/view#item/319525
> Implement clean build option

- lib/services/authentication-service.ts
- lib/services/cloud-build-service.ts
Whenever rejecting a promise an error object needs to be passed. Otherwise CLI fails to display the error message, because it tries to [meddle with the error's stack](https://github.com/telerik/mobile-cli-lib/blob/master/errors.ts#L13)
Fixes `undefined` error message
Ping @rosen-vladimirov @TsvetanMilanov @nadyaA
> Fix undefined error

- README.md
- lib/constants.ts
- lib/definitions/cloud-build-service.d.ts
- lib/services/cloud-build-service.ts
- package.json
Used to get the path to the directory where the build output may be found.
Ping @nadyaA @rosen-vladimirov @TsvetanMilanov
> Implement getCloudBuildOutputDirectory method

- lib/cloud-device-emulator.ts
- package.json
Do not dispose `$cloudDeviceEmulator` if it hasn't been used.
Do not dispose `$cloudDeviceEmulator` if in the middle of LiveSync
Bump `cloud-device-emulator` version
Ping @TsvetanMilanov @rosen-vladimirov
> Dispose $cloudDeviceEmulator correctly

- lib/cloud-device-emulator.ts
- package.json
There's no point in calling `killServer` when there is no server running. Attempting to do so will launch the server and then kill it.
In addition, fix location of `this._isCloudDeviceEmulatorInstanceInitialized = true`
> Check if server is running before killing it

- lib/services/cloud-build-service.ts
- package.json
This mimics the local build closely and may prevent some future problems.
The short-term benefit is the fact that by adding a platform the runtime's version is written in the package.json and is therefore respected in the cloud.
Ping @TsvetanMilanov @rosen-vladimirov
> Add platform before building

- lib/services/cloud-build-service.ts
- package.json
Currently we only add the platform before building the application. However, once we try to persist the `.nsbuildinfo` we fail with: `Cannot read property 'changesRequireBuildTime' of null`
The problem is that generating the `.nsbuildinfo` relies on the `.nsprepareinfo`, which is generated during prepare.
So instead of just calling add platform, change the code to call prepare platform. This way the `.nsprepareinfo` will be generated and the project will be prepared.
> Fix cloud builds by preparing the project before build

- lib/definitions/crypto-identities.d.ts
- lib/services/cloud-build-service.ts
- package.json
Pass the full mobileProvision data to prepare method, so it will not execute `security` command which is available only on macOS.
> Pass mobileProvision data to prepare

- lib/services/cloud-build-service.ts
- package.json
Currently we prepare the project AFTER zipping it. This is not correct when the prepare executes `platform add` as we end-up without the `tns-<platform>` key in the package.json inside the .zip.
> Prepare project before zipping the project

- lib/services/cloud-build-service.ts
- lib/services/git-service.ts
- package.json
Currently we create the `.gitignore` file right before calling `git push`. However, at this point the initial commit of files is already created and some special files (like `platforms` and `node_modules` directories) are pushed in the remote repository.
Fix this by creating the `.gitignore` at the beginning of the operation, before calling `git add` and `git commit`.
Also rename a method (just to make it clear what's the behavior of the method).
> Create default .gitignore before initial commit

- lib/services/git-service.ts
- package.json
If the version of git is below 2.9.0 we shouldn't use git or windows credential manager will prompt for username and password.
> Check for unsupported git version on Windows.

- lib/services/cloud-build-service.ts
- package.json
When preparing project from cloud services we do not count on local setup, so skip native preparation
Merge after - https://github.com/NativeScript/nativescript-cli/pull/2983
https://github.com/NativeScript/nativescript-cli/issues/2968
> Use skipNativePrepare for cloud builds

- lib/mobile/device/cloud-emulator-device-file-system.ts
- lib/services/cloud-build-service.ts
- lib/services/git-service.ts
- package.json
When the user `X` builds project with name `test` we create local repository with name the sha1 of the project id.
If the user `Y` creates project with the same name on the same machine we put the new project in the same local repo.
User `Y` does not have credentials for the repo of user `X` and each git operation which requires the credentials fails with 403.
The solution is to include the user email in the repo name.
Also we need to pass `userEmail` in our build request properties because we need it in our build tooling.
> Fix git builds

- lib/constants.ts
- lib/definitions/cloud-build-service.d.ts
- lib/services/cloud-build-service.ts
Build steps:
- prepare
- upload
- build
- download
The `cloudBuildService` will emit `buildStepChanged` event for each step.
Each object will have build ID, step name and a progress which will be a number between 0 and 100%.
These build steps will be used for profiling the build and some kind of progress indicator in the clients of the extension.
> Note: I will update the README.md after the review of the functionality.
> Add cloud build steps

- lib/bootstrap.ts
- lib/commands/cloud-build.ts
- lib/commands/cloud-codesign.ts
- lib/constants.ts
- lib/definitions/cloud-build-service.d.ts
- lib/definitions/cloud-codesign-service.d.ts
- lib/definitions/cloud-service.d.ts
- lib/definitions/cloud-services/build-cloud-service.d.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-codesign-service.ts
- lib/services/cloud-service.ts
- lib/services/cloud-services/build-cloud-service.ts
There is new server logic for generation of iOS codesign files. With providing apple credentials for free apple account, user can generate development .p12 and .mobileprovision files to build their project in debug configuration. The implementation is similar to already existing one for cloud build. That is why some common logic is extracted. Naming of some of the items cannot be changed as it will require many follow-up changes that might be a topic for another PR. For consistency request properties are changed to be camel case as they're expected on the server.
http://teampulse.telerik.com/view#item/346464
https://github.com/Icenium/BuilderDaemon/pull/101
> Implement codesign cloud service and command

- Gruntfile.js
- lib/services/authentication-service.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-codesign-service.ts
- lib/services/cloud-service.ts
- package.json
`tslint` has some additional rules and benefits we'd like to use.
* replace `grunt-lint` with `tslint`
* fix lint errors
* introduce `npm` scripts for launching linter
Ping @rosen-vladimirov @TsvetanMilanov @nadyaA
> Replace grunt-lint with tslint

- lib/commands/build-command-helper.ts
- package.json
Prefer lazy over eager load so that newer `nativescript-cloud` versions may perform cloud build with older `nativescript` cli versions
> Load $localBuildService lazily

- lib/bootstrap.ts
Whenever a device detection is started, we are starting a server process, which is kept alive even after CLI dies. As we are not using cloud emulators at the moment and as this causes issues when there's no network adapter on Windows, remove these lines for the moment.
> Remove cloud emulator detection

- README.md
- lib/bootstrap.ts
- lib/cloud-options-provider.ts
- lib/commands/account/account-command-base.ts
- lib/commands/account/account-list.ts
- lib/commands/account/usage.ts
- lib/commands/build-command-helper.ts
- lib/commands/cloud-build.ts
- lib/constants.ts
- lib/definitions/acccounts-service.d.ts
- lib/definitions/cloud-build-service.d.ts
- lib/definitions/cloud-options.d.ts
- lib/definitions/cloud-services/accounts-cloud-service.d.ts
- lib/definitions/cloud-services/auth-cloud-service.d.ts
- lib/definitions/cloud-services/build-cloud-service.d.ts
- lib/helpers.ts
- lib/services/accounts-service.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-services/accounts-cloud-service.ts
- lib/services/cloud-services/auth-cloud-service.ts
- lib/services/user-service.ts
- package.json
- server-configs/config-base.json
- server-configs/config-dev.json
- server-configs/config-local.json
- server-configs/config-production.json
- server-configs/config-test.json
- server-configs/config.json
Some of the cloud functionality will become paid. This requires the account abstraction.
Currently we have users and we use them in our cloud services. Now we are going to use the users as part of accounts. Each user has personal account. Also the user A can add to his/hers account the user B. This way the user B will be able to  use the subscriptions of the user A. 
This PR adds the following commands:
- `tns account` (`tns account list`) -> this command show all accounts of the current user.
- `tns account usage` -> this command show the remaining usage for each feature from the subscription of the provided account.
Added services to the public API:
- `accountsService`
- `cloudBuildService.build` requires accountId.
> Add accounts

- lib/commands/build-command-helper.ts
- lib/definitions/cloud-build-service.d.ts
- lib/services/cloud-build-service.ts
Merge after https://github.com/NativeScript/nativescript-cli/pull/3116
Remove latest commit before merging
Ping @rosen-vladimirov @nadyaA
> Enable passing additional flags to webpack

- lib/services/eula-service.ts
- package.json
- test/services/eula-service.ts
The EULA should be downloaded to a temp file as the `pipeTo` option of httpClient.httpRequest` immediately creates the file or overwrites it.
In case the download fails, we'll end up with 0KB EULA, which will trigger many incorrect behaviors on our side.
In order to fix this - move the EULA to its location after full download is finished.
> Download EULA to temp file

- lib/commands/build-command-helper.ts
- lib/definitions/cloud-build-service.d.ts
- lib/definitions/git-service.d.ts
- lib/services/cloud-build-service.ts
- lib/services/git-service.ts
We need to add the application identifier to the name of the temp git
folder. With the current name we have problem when the user changes the
application identifier of the project. When we create the temp git folder
we set the cloud remote to code commit repo X. After the app identifier is
changed we try to add again cloud remote to code commit repo Y in the same
temp git folder. This operation fails and we default to zip upload.
> Add the application id to the tmp git folder

- README.md
- lib/services/user-service.ts
The `getUserAvatar` method is failing as it is using incorrect injected dependency - nsCloudAccountsService. The correct one is `nsCloudAccountsCloudService`.
Fix README as well - the example is incorrect as it does not call the `getUserAvatar` method.
> Fix getUserAvatar method

- lib/commands/build-command-helper.ts
- lib/services/cloud-build-service.ts
If we do not interpolate the data in the project's `app.gradle` file, one is bound to end up with a `__PACKAGE__` application indentifier upon multiple subsequent cloud builds.
> Interpolate app.gradle file prior to build

- lib/services/upload-service.ts
In case the upload to S3 fails, we dismiss the real error object. However, it may contain additional property: proxyAuthenticationRequired, which shows the caller that the cause of the failure is a proxy, requiring authentication.
So pass the value to the `errors.fail` method, which will construct correct error object.
NOTE: Merge after https://github.com/telerik/mobile-cli-lib/pull/1033 (transpilation will fail before that)
> Respect proxyAuthenticationRequired property during upload

- lib/services/cloud-build-service.ts
- package.json
Enable setting a custom value for CLI version during cloud builds.
Said value is set through an environment variable, named `TNS_CLI_CLOUD_VERSION`
Ping @rosen-vladimirov @nadyaA
> Enable building with custom CLI version

- lib/services/cloud-build-service.ts
- package.json
Currently the env variable `TNS_CLI_CLOUD_VERSION` is used to set the runtime version in the cloud, not the CLI version. Fix the code, so the variable will be used as it has been intended - to set the CLI version in the cloud.
> Fix using custom CLI version in the cloud

- lib/cloud-options-provider.ts
- lib/commands/config/config-apply.ts
- lib/commands/config/config-set.ts
- lib/definitions/cloud-options.d.ts
- lib/definitions/server-config-manager.d.ts
- lib/server-config-manager.ts
Each server PR build produces test dns record with api version in the
following format -> `pr<pr-number>`. To make the development cycle easier
we can add --apiVersion flag to the config apply/set commands which will
override the default apiVersion of the provided configuration. This way
when we want to use a specific server PR we can just execute `tns config
apply test --apiVersion pr<pr-number>`.
> Add command flags to change global server config

- lib/services/server/server-services-proxy.ts
In case requests to our server are blocked by proxy, in most of the cases html is returned instead of JSON.
In this case we do not show correct error, but fail with `Unexpected token < in JSON at position 0`
This generates support as users are unable to understand the real cause of the problem.
In order to give them more information, throw error with the returned body.
> Throw correct error when requests to our server are blocked

- lib/services/cloud-codesign-service.ts
Reported in this issue - https://github.com/NativeScript/sidekick-feedback/issues/92
It looks like apple is having sporadic maintenance on the developer site and some of our users are experiencing strange 403 Forbidden error. Seem like fastline are having similar issue as well - https://github.com/fastlane/fastlane/issues/10323
> Throw meaningful error if apple service is unavailable.

- lib/services/cloud-project-service.ts
Add the project name in the cloud cleanup output. This was requested from
our QAs.
> Add project name in the cleanup output

- lib/definitions/version-service.d.ts
- lib/services/cloud-build-service.ts
- lib/services/version-service.ts
- test/services/version-service.ts
Fix getting runtime and cli versions for cloud builds by reading the
package.json of the project just before sending the request. Currently
we are relying on the nativescriptData passed by the caller, but in case
this is the first build for this platform, the nativeScriptData contains
only the id of the project. However, before sending the build request,
we are adding the platform, so the package.json contains the required
version of the runtime. So instead of using some logic to determine the
runtime version, just read the package.json.
Also remove the default fallbacks for CLI and runtime (3.0.0). From now
on, whenever we are unable to find version that should be used in the
cloud, an error will be raised.
This fixes the case when the first cloud build is executed with version
3.0.x of …
> Fix getting runtime and cli versions for cloud builds

- README.md
- lib/commands/account/usage.ts
- lib/definitions/server/server-accounts-service.d.ts
The current `licenseExpiration` property represents when the cloud builds
usage will be rest. For the monthly licenses this reset date is the same
as the license expiration. But we don't have only monthly licenses. We
have complimentary licenses with custom expiration date, business and
enterprise licenses which have yearly expiration date.
That's why our server now returns 2 new properties in the usage info.
`licenseExpirationDate` which is the real license expiration date and
`resetDate` which is the monthly usage reset date. The `licenseExpiration`
property is not deleted for backwards compatibility.
> Add new subscription expiration properties

- lib/constants.ts
Set the correct URL for Kinvey Free EULA. Currently it redirects to the Kinvey site, but it will be updated to contain a PDF file with the correct EULA
> fix(kinvey): Set correct url for Kinvey Free EULA

- lib/bootstrap.ts
- lib/commands/build-command-helper.ts
- lib/commands/bundle-validator-base-command.ts
- lib/commands/cloud-build.ts
- lib/commands/cloud-deploy.ts
- lib/commands/cloud-run.ts
- lib/definitions/build-command-helper.d.ts
- lib/definitions/cloud-build-service.d.ts
- lib/definitions/cloud-service.d.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-codesign-service.ts
- lib/services/cloud-project-service.ts
- lib/services/cloud-publish-service.ts
- lib/services/cloud-service.ts
Introduce `cloud run|deploy` commands.
Designed to work as the conventional `run|deploy` commands but build in the cloud instead of locally.
**NB!** Remove latest commit before merging
> Introduce cloud run|deploy commands 

- lib/definitions/application-service.d.ts
- lib/definitions/version-service.d.ts
- lib/services/application-service.ts
- lib/services/version-service.ts
- test/services/version-service.ts
In case the user has a prerelease of the runtime installed, use the latest prerelease of CLI during cloud builds.
Tested with:
```
> semver.maxSatisfying(versions, "~4.0.0-0")
"4.0.0-2018-03-07-10905"
> semver.maxSatisfying(versions, "~3.4.0-0")
"3.4.3"
```
In addition - pass `config` object to `shouldInstall` method.
**NB!** This is not breaking, because this method is currently unused.
> Respect runtime prereleases

- lib/commands/cloud-run.ts
Whenever performing cloud builds project should not be prepared natively
> Pass skipNativePrepare

- lib/bootstrap.ts
- lib/commands/bundle-validator-base-command.ts
- lib/commands/cloud-build.ts
- lib/commands/cloud-deploy.ts
- lib/definitions/polyfill-service.d.ts
- lib/services/polyfill-service.ts
- lib/services/version-service.ts
- test/services/version-service.ts
Includes:
* Introduce and reuse the new `nsCloudPolyfillService`
* Use correct `NATIVESCRIPT_PROPS_INTERNAL_DELIMITER` constant - it was changed in CLI
Ping @rosen-vladimirov @Fatme
> Introduce polyfill mechanism

- package.json
In case extension is not installed, but user tries to use any command from it, CLI tries to find out in which extension the command is registered. It works by checking all packages in npm that have the `nativescript:extension` keyword.
After that it reads their package.json and searches for nativescript.commands array.
So prepare the `nativescript-cloud` by adding all commands to the correct place in package.json. Add required keyword and some addtional ones.
> feat: Improve package.json, so CLI can detect this as extension

- lib/services/cloud-build-service.ts
When trying to build the application with webpack, the locally prepared files are incorrect. The problem is that the the bundle value is not passed to the prepare method - we have hardcoded false. This way the local files are prepared without webpack and the result application is not working.
Pass correct value, so the local files will be correct.
> fix: Trying to build application with webpack produces incorrect local files

- lib/commands/cloud-run.ts
In case when `tns cloud run` command is executed and the local environment is not correctly configured, {N} CLI shows a prompt with 4 options (configure for local builds, configure for cloud builds, configure for both - local and cloud builds, setup manually) to configure automatically the environment. This prompt should not be shown in case when cloud commands are executed.
We discussed the situation and agreed the whole `validatePlatform` method is not needed for cloud run command.
This PR fixes the behaviour with missing await.
> Remove validatePlatform for run command

- lib/services/cloud-publish-service.ts
When the cloud publish fails with non ITMS error (e.g. not accepted
license agreement, wrong password), we show only part of the error which
can be `The request could not be completed because:` and the real reason
is hidden. We decided to show the whole stderr to solve this problem.
In case of ITMS error, it will be displayed and the github issues
information displayed by fastlane will be hidden because it is displayed
on the stdout which is filtered.
> Print the publish error

- lib/bootstrap.ts
- lib/services/kinvey-eula-service.ts
- lib/services/server/mbaas/kinvey-request-service.ts
- package.json
In case we send requests to Kinvey, we check if Kinvey EULA has been accepted. This is not required anymore, so remove the check from the `kinvey-request-service`.
As the nsCloudKinveyEulaService has been publicly exposed, we cannot remove it without bumping the major version. So keep it in the code until we prepare for 2.0.0 release
> feat: Remove check for Kinvey EULA when sending requests

- lib/commands/cloud-codesign.ts
- lib/services/application-service.ts
In older CLI versions the `checkForChanges` method has different arguments. Fix the backwards compatibility by checking CLI's version and call the method with correct args.
Fix the `cloud codesign` command.
> Integrate the latest changes in {N} CLI

- lib/mobile/device/cloud-emulator-device-file-system.ts
The underlying interface for Device File System has changed, so implement the new method that is required.
> fix: transpilation is failing due to missing implementation

- lib/services/cloud-build-service.ts
Rel to: https://github.com/NativeScript/nativescript-cli/pull/3692
> fix: make android build faster

- lib/services/cloud-build-service.ts
Whenever we want to use Hot Module Reload, we have to pass `--hmr` option to the build in the cloud.
Also move the passing of `--env` flags to a separate `if` as `--env` can now be passed with `--hmr` and `--bundle` flags.
> feat: pass --hmr to cloud build

- lib/services/cloud-build-service.ts
- lib/services/git-service.ts
- package.json
Using cloud build with Hot Module Replacement is not working when git is used as it modifies the line endings. Most of the templates are published from Windows machine, so the line endings in them are `\r\n`.
The local prepare of the project produces bundle.js with `hotCurrentHash = <value 1>`. Once we use git to push the files in the cloud, the line endings are `\n`. The `bundle.js` produced in the cloud contains `hotCurrentHash = <value 2>`.
After the built .apk is downloaded from the cloud and installed on device, CLI does not apply full sync as it thinks the local files are the same as the ones in the cloud.
In order to fix this, set `core.autocrlf` to false in the local codecommit repo. This way the line endings will be the same and the `hotCurrentHash` should be the same in the …
> fix: hmr is not working in some cases

- lib/services/cloud-services-policy-service.ts
It seems like the link for privacy management we used from OneTrust is not working anymore. replacing it with a new one after consultation with legal
> fix: onetrust link

- package.json
- server-configs/config-base.json
- server-configs/config.json
Our server is now reachable through new domain - *.nativescript.cloud.
Also the api version is now v3
> Update the server config

- package.json
Fix the master build by updating `@types/promise-retry` to latest version. Currently the build fails as `@types/promise-retry`'s 1.1.1 version depends on `@types/retry` package with `*`, which means it always installs the latest version.
The `.d.ts` files in the latest `@types/retry` package are for newer version, which has breaking change in the API, so our transpilation fails. The issue is fixed in `@types/promise-retry` by using specific version of the `@types/retry` package.
> fix: update @types/promise-retry to latest version

- lib/account-utils.ts
- lib/bootstrap.ts
- lib/cloud-options-provider.ts
- lib/commands/dev-login.ts
- lib/constants.ts
- lib/definitions/account-utils.d.ts
- lib/definitions/authentication-service.d.ts
- lib/definitions/cloud-options.d.ts
- lib/definitions/server/server-auth-service.d.ts
- lib/helpers.ts
- lib/services/authentication-service.ts
- lib/services/kinvey-user-service.ts
- lib/services/server/server-auth-service.ts
- lib/services/server/server-services-proxy.ts
Allow users with Single-Tenant Cloud Instance to login and perform cloud builds.
> Send kinvey instanceId header to the server.

- README.md
- lib/account-utils.ts
- lib/bootstrap.ts
- lib/cloud-config-manager.ts
- lib/commands/config/config-apply.ts
- lib/commands/config/config-get.ts
- lib/commands/config/config-reset.ts
- lib/commands/config/config-set.ts
- lib/definitions/cloud-config-manager.d.ts
- lib/definitions/server/server-services.d.ts
- lib/services/server/mbaas/mbaas-proxy.ts
- lib/services/server/server-auth-service.ts
- lib/services/server/server-services-proxy.ts
- lib/services/user-service.ts
- server-configs/config-local.json
- server-configs/config-production.json
- server-configs/config-test.json
- server-configs/config.json
Add `nsCloudConfigManager` to the public API. It should provide methods for managing the cloud configuration and for listing all cloud services domain names.
This PR also removes the unused cloud services.
> Add nsCloudConfigManager to the public API

- lib/services/eula-service-base.ts
- package.json
- tslint.json
As the method for lock of accepting EULA is not awaited, first time when `tns accept eula` is called, it writes `false` in the `user-settings.json` file. So EULA is not actually accepted.
Await the execution, so correct EULA hash is written in the file.
Update devDependencies to latest TypeScript related versions as CLI had updated its own versions and current build fails. Remove `--type-check` from tslint spawn as the option is deprecated.
Remove tslint rule as it is also deprecated.
>  fix: EULA is not accepted correctly first time 

- lib/services/eula-service-base.ts
- package.json
- test/services/eula-service.ts
In case the http request for downloading EULA returns 304, we should not overwrite existing EULA as the downloaded file is empty.
> fix: do not overwrite EULA in case download returns 304

- lib/bootstrap.ts
- lib/commands/build-command-helper.ts
- lib/commands/clean/clean-cloud-workspace.ts
- lib/commands/cloud-build.ts
- lib/commands/cloud-codesign.ts
- lib/commands/cloud-deploy.ts
- lib/commands/cloud-dev-apple-login.ts
- lib/commands/cloud-publish.ts
- lib/commands/cloud-run.ts
- lib/commands/interactive-cloud-command.ts
- lib/definitions/cloud-process-service.d.ts
- lib/services/cloud-apple-service.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-codesign-service.ts
- lib/services/cloud-project-service.ts
- lib/services/cloud-publish-service.ts
- lib/services/cloud-service.ts
- lib/services/lock-service.ts
- lib/services/process-service.ts
In CLI the `processService` has been removed and the Ctrl + C signal is handled in a different manner. To make the `nativescript-cloud` compatible with both official CLI and the one in developement, introduce process-service in `nativescript-cloud` that wraps the original one, if it exists.
> This service should be removed when CLI 5.4.0 is the minimum required one.
>  fix: handle CLI's changes for Ctrl + C

- lib/commands/account/account-list.ts
- lib/commands/account/features.ts
- lib/commands/account/usage.ts
- lib/services/cloud-apple-service.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-codesign-service.ts
- lib/services/cloud-project-service.ts
- lib/services/cloud-publish-service.ts
- lib/services/cloud-service.ts
Due to latest CLI changes, some logger APIs have been deprecated. Use correct new APIs.
Also using `logger.out` prints tables incorrectly - use `logger.info` which is the correct way now.
NOTE: For example output of `tns account` was not showing table at all. This is fixed now.
> fix: tables output is not correct

- lib/services/cloud-build-service.ts
- package.json
Currently in case you do not want to use webpack for your build (in Sidekick for example), we do not pass any bundle related options to the cloud. However, all new projects have `nsoconfig.json` in which we set that we want to use hmr workflow.
So once the project is uploaded in the cloud, we'll build it with webpack. The local prepare will not use webpack.
This breaks the LiveSync for Android, which directly syncs the files in the application on device. As the cloud build is with webpack we have `bundle.js`, `vendor.js`, etc. there. Syncing files like `main-view-model.js` is not respected when the application is started as the entry point of the build application points to starter.js file.
For iOS this works as once the application is built, we livesync the locally prepared files on …
> fix: cloud build should use same bundle options as locally

- lib/services/cloud-build-service.ts
- package.json
Currently publish commands fail to build the application when `useLegacyWorkflow` is set to false in nsconfig.json. The error happens during project preparation in the cloud with error `The options --release and --hmr cannot be used simultaneously`.
This happens as by default we do not pass `--release` to cloud publish commands, so CLI does not set `options.hmr` to false. So in the cloud we send both `--release` and `--hmr` options and the build fails.
To fix this, set `--no-hmr` when we build in release configuration.
> fix: publish commands fail to build app

- lib/commands/cloud-build.ts
- lib/definitions/cloud-build-service.d.ts
- lib/services/cloud-build-service.ts
- package.json
CLI 6.0 prepares the project on initial sync for all livesync related commands and the `nativescript-cloud` tries to prepare it again. Hopefully there is a caching based on the platforms for which the webpack compilation is started. This way, a second webpack compilation is not started, but the prepare method is called for the second time. This led to the problem that nativePrepare method is called twice. However, for cloud related operations (when `skipNativePreapare` is true), `prepareNativePlatform` method only checks if there are changes in the project. This way, `checkForChanges` method is called twice. In order to remove the second `checkForChanges` we can remove preparing the project from cloud lib. This will led to the issue that if `tns cloud build ` command is executed and after …
> fix: don't call prepare method twice on livesync related commands

- lib/cloud-operation/cloud-operation-v1.ts
- lib/commands/build-command-helper.ts
- lib/commands/cloud-build.ts
- lib/definitions/cloud-build-service.d.ts
- lib/services/cloud-build-service.ts
- lib/services/cloud-service.ts
1. Add support for `--aab` flag for `tns cloud build`
2. Snooze log polling so that two subsequent polls do not overlap.
3. After the cloud build completes, check if new logs were generated between the last poll and the operation status change.
> Support aab build flag

- lib/commands/build-command-helper.ts
- lib/services/cloud-build-service.ts
- package.json
Do not generate `qrData` after cloud build with `aab` flag. A user cannot download and install an aab package directly on an Android device as they can with an apk package, so the `qrData` is irrelevant. Additionally, the `originalUrl`, returned as part of the `qrData` is incorrect as it points to an apk file. We rename this apk file as part of the download step of a cloud build operation, so the local file has the correct extension, but the URL is incorrect for the user.
> Remove qr data aab

- .travis.yml
- lib/cloud-android-bundle-validator-helper.ts
The `nativescript` is not correctly downloaded when installing the dependencies. It seems it is cached and travis relies on this cache in order to use it.
So, we need to set `cache: npm: false` inside `travis.yaml`. This way, `npm install` will always get the dependencies from github instead of the local cache.
> fix: add validateDeviceApiLevel to cloud-bundle-validator-helper

- lib/services/cloud-codesign-service.ts
- package.json
The currently used nativescript-doctor version is very old and it has non-direct dependency to the `natives` package, which does not work with latest Node.js versions. It needs to be updated every time when a new Node.js is released.
The latest nativescript-doctor version does not depend on natives package, so the errors with `natives` packages are not propagated anymore.
Fixes issue https://github.com/NativeScript/sidekick-feedback/issues/434
> fix: update nativescript-doctor to latest version

- docs/cloud-publish-android.md
- lib/cloud-options-provider.ts
- lib/commands/cloud-publish.ts
- lib/definitions/cloud-options.d.ts
- lib/definitions/cloud-publish-service.d.ts
- lib/definitions/server/server-build-service.d.ts
- lib/services/cloud-publish-service.ts
- package.json
The new google play publish api requires a release status. We need to
provide a way to pass this status to our build machines.
> Add --androidReleaseStatus flag

- lib/bootstrap.ts
- lib/services/eula-service-base.ts
- lib/services/eula-service.ts
- lib/services/kinvey-eula-service.ts
- lib/services/policy-service.ts
- lib/services/temp-service.ts
- package.json
- test/services/eula-service.ts
Currently temp files are not deleted in some cases. Use the tempService from CLI 6.4 or fallback to `temp` module in case CLI is older.
Must be merged after https://github.com/NativeScript/nativescript-cli/pull/5238
> fix: temp files should be deleted
